services:
  - type: web
    name: metodikish
    runtime: node
    plan: free
    buildCommand: |
      cd server && npm install
      cd ../client && npm install && npm run build
      cd ../admin && npm install && npm run build
    startCommand: cd server && node index.js
    envVars:
      - key: PORT
        value: 3000
      - key: API_URL
        value: https://ustozlargaxizmatrobot.onrender.com
    disk:
      name: data
      mountPath: /opt/render/project/data
      sizeGB: 1

  - type: worker
    name: metodikish-bot
    runtime: node
    plan: free
    buildCommand: cd bot && npm install
    startCommand: cd bot && node bot.js
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: API_URL
        value: https://ustozlargaxizmatrobot.onrender.com
