services:
  - type: web
    name: metodikish
    runtime: node
    plan: free
    buildCommand: |
      cd server && npm install
      cd ../client && npm install && npm run build
      cd ../admin && npm install && npm run build
    startCommand: cd server && node index.js
    envVars:
      - key: PORT
        value: 10000
      - key: BOT_TOKEN
        sync: false
      - key: WEBHOOK_URL
        value: https://ustozlargaxizmatrobot.onrender.com
    disk:
      name: data
      mountPath: /opt/render/project/data
      sizeGB: 1
