# Generated by Django 4.2.11 on 2026-07-12 18:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Order number')),
                ('full_name', models.CharField(max_length=255, verbose_name='Full name')),
                ('region', models.CharField(max_length=100, verbose_name='Region')),
                ('district', models.CharField(max_length=100, verbose_name='District')),
                ('school_name', models.CharField(max_length=255, verbose_name='School name')),
                ('home_address', models.CharField(max_length=500, verbose_name='Home address')),
                ('subject', models.CharField(max_length=100, verbose_name='Subject')),
                ('grade', models.CharField(max_length=50, verbose_name='Grade')),
                ('topic', models.CharField(max_length=255, verbose_name='Topic')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAYMENT_CHECKING', 'Payment Checking'), ('PAID', 'Paid'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'orders',
                'db_table': 'orders_order',
                'ordering': ['-created_at'],
            },
        ),
    ]
