# Generated by Django 4.2.11 on 2026-07-12 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
                ('card_number', models.CharField(max_length=20, verbose_name='Card number')),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to='receipts/', verbose_name='Receipt image')),
                ('receipt_hash', models.CharField(blank=True, max_length=255, verbose_name='Receipt hash')),
                ('image_hash', models.CharField(blank=True, max_length=255, verbose_name='Image hash')),
                ('status', models.CharField(choices=[('WAITING', 'Waiting'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='WAITING', max_length=20, verbose_name='Status')),
                ('admin_comment', models.TextField(blank=True, verbose_name='Admin comment')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='orders.order', verbose_name='Order')),
            ],
            options={
                'verbose_name': 'payment',
                'verbose_name_plural': 'payments',
                'db_table': 'payments_payment',
                'ordering': ['-created_at'],
            },
        ),
    ]
